---
kind: pipeline
name: testing

platform:
  os: linux
  arch: amd64

steps:
- name: release
  pull: always
  image: node:12
  commands:
  - apt-get install g++ build-essential
  - npm install -g node-gyp
  - make release
