---
kind: pipeline
name: testing

platform:
  os: linux
  arch: amd64

steps:
- name: release
  image: node:13
  commands:
  - make install
  - make build

- name: publish
  image: plugins/gh-pages
  settings:
    username: appleboy
    ssh_key:
      from_secret: ssh_key
    pages_directory: dist/files
